language: node_js
node_js:
  - '10.15'
  - '11.15'
  - '12.2'
branches:
  only:
    - master
cache: yarn
script: yarn test:ci
before_deploy:
  - yarn build-storybook
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  skip_cleanup: true
  on:
    node_js: '12.2'
    branch: 'master'
